name: ReBuild
on:
  push:
  workflow_dispatch:

env:
  SB_pathPrefix: "/${{ github.event.repository.name }}/"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache NPM Build
        id: cache
        uses: actions/cache@v4
        with:
          path: dist
          key: stacbrowser2
      
      - name: NPM Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      
      - name: NPM Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build -- --historyMode=hash 

      - name: Overwrite Config.js
        run: | 
          # Copy config into cached build
          diff config.js dist/config.js
          cp config.js dist/config.js
          #cat dist/config.js
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload just 'dist/' folder
          path: 'dist'
        
  # https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
